[[publishing]]
== Publishing a processed dataset to GBIF.org

IMPORTANT: https://edna-tool.gbif-uat.org/[*THE_TOOL (GBIF eDNA metabarcoding data converter)*] is currently hosted in the GBIF [.underline]#test environment#, and is still a prototype under development. Currently, THE_TOOL can be used to produce a Darwin Core Archive, that can be "published to" and viewed in the https://www.gbif-uat.org/[GBIF test environment (UAT)], but it [.underline]#cannot publish them directly to GBIF.org#.

WARNING: Files uploaded to THE_TOOL and files produced by THE_TOOL are currently stored in the GBIF test environment that cannot be considered a stable repository. Keep a local copy of important files! 

NOTE: THE_TOOL may possibly become a hosted repository, so that endpoints generated by THE_TOOL can be registered with and indexed by with GBIF, OBIS, etc. It may also be a future possibility to be able to publish directly to GBIF.org from THE_TOOL.

TIP: see this https://data-blog.gbif.org/post/installations-and-hosting-solutions-explained/[blog post] on general possibilities to publish and host datasets.

=== Publishing through IPT

The https://www.gbif.org/ipt[Integrated Publishing Toolkit] — commonly referred to as the IPT — is free open-source software developed by GBIF and used by organizations around the world to create and manage repositories for sharing biodiversity datasets. If you have access to an IPT and know how to use it, you can download the DwC-A produced by THE_TOOL and publish it through an IPT. By doing so you will unfortunately lose the possibility and functionality of THE_TOOL for updating, re-processing and "analysing" the dataset.

THE_TOOL should be able to produce fully publishable Darwin Core Archives, with no need for further changes or additions in the IPT. Archives dowloaded and modified (e.g. in the IPT), will not subsequently be possible to modify or update in THE_TOOL.


*Publishing of an archive from THE_TOOL via IPT*

* Download the DwC-A (archive.zip) from THE_TOOL.
* login to the IPT.
* Press *Magage Resources*.
* Press *Create new*.
* Give your dataset a *Shortname*.
* Select _Occurrence_ under *Type*.
* Choose *Import from an archived resource*.
* Press *Choose file*, and select your file from the computer.
* Press *Create*.
* Validate and verify that the data looks as expected.
* Modify and add information as needed.
* Publish the data.

=== Registering an archive hosted elsewhere

A Darwin Core Archive produced with THE_TOOL may be put elsewhere on the web – preferably in a stable repository (e.g. Zenodo, GitHub) – and can then be indexed by GBIF. This requires somebody to register the new resource with GBIF.

*Publishing of an archive from THE_TOOL by hosting elsewhere and registering the resource*

* Download the DwC-A (archive.zip) from THE_TOOL.
* Put the archive somewhere in a stable repository, so you have an URL: www/xxx/archive.zip
* Register the dataset with the relevant publisher in the GBIF registry (How to do that?).