[[publishing]]
== Publishing a dataset to GBIF.org

IMPORTANT: *https://edna-tool.gbif-uat.org/[THE_TOOL (GBIF eDNA metabarcoding data converter)]* is currently hosted in the GBIF [.underline]#test environment#, and is still a prototype under development. Currently, it can be used to produce a Darwin Core Archive, that can be viewed in the https://www.gbif-uat.org/[GBIF test environment (UAT)], but it [.underline]#cannot publish them directly to GBIF.org#.

WARNING: Files uploaded to the tool and files produced by the tool are currently stored in the GBIF test environment, that cannot be considered a stable repository. Download files you wish to have for future use! 

NOTE: It may be a future possibility that THE_TOOL becomes a hosted repository, where endpoints generated by the tool can be registered with and indexed by with GBIF, OBIS, etc. It may be a future possibility to be able to publish directly to GBIF.org from THE_TOOL.

=== Publishing through IPT

The https://www.gbif.org/ipt[Integrated Publishing Toolkit] — commonly referred to as the IPT — is free open-source software developed by GBIF and used by organizations around the world to create and manage repositories for sharing biodiversity datasets. If you have access to an IPT and know how to use it, you can download the DwC-A produced by THE_TOOL and publish it through the IPT. By doing so you will unfortunately lose the possibility and functionality of THE_TOOL for re-processing and updating the datset.

Publish through IPT

* Download the DwC-A (archive.zip) from THE_TOOL
* login to the IPT
* Press *Magage Resources*
* Press *Create new*
* Give your dataset a *Shortname*
* Select _Occurrence_ under *Type*
* Choose *Import from an archived resource*
* Press *Choose file*, and select your file from the computer
* Press *Create*

