[[publishing]]
== Publishing a processed dataset to GBIF.org

IMPORTANT: https://edna-tool.gbif-uat.org/[*the MDT (GBIF eDNA metabarcoding data converter)*] is currently hosted in the GBIF [.underline]#test environment#, and is still a prototype under development. Currently, the MDT can be used to produce a Darwin Core Archive, that can be "published to" and viewed in the https://www.gbif-uat.org/[GBIF test environment (UAT)], but it [.underline]#cannot publish them directly to GBIF.org#.

WARNING: Files uploaded to the MDT and files produced by the MDT are currently stored in the GBIF test environment that cannot be considered a stable repository. Keep a local copy of important files! 

NOTE: the MDT may possibly become a hosted repository, so that endpoints generated by the MDT can be registered with and indexed by with GBIF, OBIS, etc. It may also be a future possibility to be able to publish directly to GBIF.org from the MDT.

TIP: see this https://data-blog.gbif.org/post/installations-and-hosting-solutions-explained/[blog post] on general possibilities to publish and host datasets.

=== Publishing through IPT

The https://www.gbif.org/ipt[Integrated Publishing Toolkit] — commonly referred to as the IPT — is free open-source software developed by GBIF and used by organizations around the world to create and manage repositories for sharing biodiversity datasets. If you have access to an IPT and know how to use it, you can download the DwC-A produced by the MDT and publish it through an IPT. By doing so you will unfortunately lose the possibility and functionality of the MDT for updating, re-processing and "analysing" the dataset.

the MDT should be able to produce fully publishable Darwin Core Archives, with no need for further changes or additions in the IPT. Archives dowloaded and modified (e.g. in the IPT), will not subsequently be possible to modify or update in the MDT.


*Publishing of an archive from the MDT via IPT*

* Download the DwC-A (archive.zip) from the MDT.
* login to the IPT.
* Press *Magage Resources*.
* Press *Create new*.
* Give your dataset a *Shortname*.
* Select _Occurrence_ under *Type*.
* Choose *Import from an archived resource*.
* Press *Choose file*, and select your file from the computer.
* Press *Create*.
* Validate and verify that the data looks as expected.
* Modify and add information as needed.
* Publish the data.

=== Registering an archive hosted elsewhere

A Darwin Core Archive produced with the MDT may be put elsewhere on the web – preferably in a stable repository (e.g. Zenodo, GitHub) – and can then be indexed by GBIF. This requires somebody to register the new resource with GBIF.

*Publishing of an archive from the MDT by hosting elsewhere and registering the resource*

* Download the DwC-A (archive.zip) from the MDT.
* Put the archive somewhere in a stable repository, so you have an URL: www/xxx/archive.zip
* Register the dataset with the relevant publisher in the GBIF registry (How to do that?).