[[tips_tricks]]
== Tips/Tricks and Advanced Usage 

=== Exclude samples and/or OTUs

Datasets most often include control samples (negative coltrols, blanks, positive controls, etc.). Such control samples do not represent relevant biodiversity and should be removed, as only real biological/environmental samples producing data that seems trustworthy should be shared. Likewise some sequences/OTUs may be suspected contamination (e.g. DNA from humans, pets, classical food items like tomato, potato, chicken, etc.). These should also be removed if possible.

TIP: The MDT will not include samples that are not present in both the *Samples* and *OTU_table*, and will not include OTUs that are not present in both the *Taxonomy* and *OTU_table* tables. Deleting (rows or IDs) of unwanted OTUs or Samples from the Taxonomy or Samples table means that they will be excluded from the final data although they are present in the OTU_table. This is thus an easy way of excluding OTUs or Samples – e.g. negative control samples, suspected contaminant species – from the data. NB: There will be warnings about the imperfect overlap of IDs during processing.

=== Using MDT through API

Some users have data in an already structured system and may want to build a publication pipeline that runs the MDT using API. This https://github.com/gbif/metabarcoding-data-toolkit-backend?tab=readme-ov-file#api[section in the MDT backend GitHub^] describes the API methods needed to run a dataset through the MDT, from raw data files to a Darwin Core Archive, published to GBIF.org. When running the MDT with APIs, it is possible to review the dataset through the UI at any step during the API interaction.

=== Exporting a PhyloSeq object for the MDT

Users analysing their metabarcoding data in the r-package PhyloSeq may use these simple functions to save the data as MDT compatible files. (NB: unless the PhyloSeq data already includes all the recommended fields for GBIF publishing and uses DwC terms for fields, further preparations will be needed (see <<preparation_structure>>). 

==== From PhyloSeq to Excel

[source,r]
----
# Load necessary libraries
library(phyloseq)
library(openxlsx)

# Function to save Excel workbook
phyloseq_to_MDT_excel <- function(physeq, filename = "Phyloseq_Tables.xlsx") {
  # Create a new Excel workbook
  wb <- createWorkbook()
  
  # Save OTU Table
  otu_table_df <- data.frame(otu_table(physeq))
  addWorksheet(wb, "OTU_table")
  writeData(wb, "OTU_table", cbind(id = rownames(otu_table_df), otu_table_df))
  
  # Save Sample Data
  sample_data_df <- data.frame(sample_data(physeq))
  addWorksheet(wb, "Samples")
  writeData(wb, "Samples", cbind(id = rownames(sample_data_df), sample_data_df))
  
  # Save Taxonomy Table
  tax_table_df <- data.frame(tax_table(physeq))
  addWorksheet(wb, "Taxonomy")
  writeData(wb, "Taxonomy", cbind(id = rownames(tax_table_df), tax_table_df))
  
  # Save the workbook
  saveWorkbook(wb, filename, overwrite = TRUE)
}

# Example usage
# Replace 'your_phyloseq_object' with your actual phyloseq object
# phyloseq_to_MDT_excel(your_phyloseq_object)
----

==== From PhyloSeq to tsv


[source,r]
----
# Load necessary libraries
library(phyloseq)

# Function to save phyloseq tables as TSV files
phyloseq_to_MDT_tsv <- function(physeq){
  # Save OTU Table
  otu_table_df <- data.frame(otu_table(physeq))
  write.table(otu_table_df, file = "OTU_table.tsv", sep = "\t", quote = FALSE, row.names = TRUE, col.names = NA)
  
  # Save Sample Data
  sample_data_df <- data.frame(sample_data(physeq))
  write.table(cbind(id = rownames(sample_data_df), sample_data_df), 
              file = "Samples.tsv", sep = "\t", quote = FALSE, row.names = TRUE, col.names = NA)
  
  # Save Taxonomy Table
  tax_table_df <- data.frame(tax_table(physeq))
  write.table(cbind(id = rownames(tax_table_df), tax_table_df), 
              file = "Taxonomy.tsv", sep = "\t", quote = FALSE, row.names = TRUE, col.names = NA)
}

# Example usage
# Replace 'your_phyloseq_object' with your actual phyloseq object
# phyloseq_to_MDT_tsv(your_phyloseq_object)
----

[[extract_examples]]
=== Generating examples/templates from existing datasets in GBIF.org  

This section describes how to generate example files from existing metabarcoding datasets published through the *GBIF Metabarcoding Data Toolkit* (MDT). These files can be used as templates or example data for training purposes.

[discrete]
==== Step 1: Find and download an MDT dataset

. Use e.g. this proxy search to see a list of some of the MDT datasets on GBIF:  
  https://www.gbif.org/dataset/search?q=MDT

. Click on a dataset of interest. On the dataset page, scroll to the bottom to find the *GBIF registration* section.

. Download the two relevant files:
  * *Darwin Core Archive*: `archive.zip`
  * *BIOM 2.1* file: `data.biom.h5`

These typically have URLs like:

----
https://hosted-datasets.gbif.org/metabarcoding/.../archive.zip
https://hosted-datasets.gbif.org/metabarcoding/.../data.biom.h5
----

. Place both files in a folder of your choice, e.g. `my_dataset_folder`.

[discrete]
==== Step 2: Download the processing script

. Download the script link:../example_data/process_biom_and_meta.py[`process_biom_and_meta.py`] and save it in a convenient location, such as your home directory or a `scripts/` folder.

[discrete]
==== Step 3: Set up your Python environment

If you don’t already have the required packages installed, set up a virtual environment:

[source,shell]
----
python3 -m venv .venv
source .venv/bin/activate   # Use .venv\Scripts\activate on Windows

pip install pandas biom-format requests
----

[discrete]
==== Step 4: Run the script

Make sure you are in the folder where you saved the script, and run:

[source,shell]
----
python3 process_biom_and_meta.py /path/to/my_dataset_folder
----

Replace `/path/to/my_dataset_folder` with the path to the folder containing both `data.biom.h5` and `archive.zip` (or an unzipped `archive/` folder containing `meta.xml`).

Example:

[source,shell]
----
python3 process_biom_and_meta.py test
----

[discrete]
==== Step 5: Output files

The script will create the following files in the same folder:

[cols="1,3", options="header"]
|===
| File Name       | Description
| OTU_table.csv   | OTU Table (rows = taxa) (extracted from the BIOM file)
| Samples.csv     | Sample metadata (extracted from the BIOM file)
| Taxonomy.csv    | Sequences and taxonomic information (extracted from the BIOM file)
| Study.tsv       | Default/global values for various terms (extracted from `meta.xml`)
|===

These files correspond more or less to the files uploaded to the MDT by the publisher, with all terms/fields  mapped. The files can e.g. be used as templates for your own datasets or as example data for training.


////
=== Getting the taxonomy into shape
////

<<<