[[background_resources]]
== Background Material and Resources

=== GBIF and DNA

GBIF provides access to extensive biodiversity data, primarily focused on species occurrences, including where and when species have been recorded. These records, gathered from collections, surveys, and citizen science efforts, contain species names, observation dates, locations, and other important details. In addition to traditional biodiversity records, GBIF also supports https://www.gbif.org/dna[DNA-associated data], such as DNA metabarcoding datasets. A general guide – https://doi.org/10.35035/doc-vf1a-nr22[Publishing DNA-derived data through biodiversity data platforms] – was released in 2021 to assist with these specific data types. However, consultations with the GBIF network and research community in 2022 and 2023 highlighted the need for user-friendly tools to facilitate the formatting and publishing of DNA metabarcoding data in particular.

The *Metabarcoding Data Toolkit (MDT)* was developed to address this need.

=== The GBIF Metabarcoding Data Programme

In October 2024, https://www.gbif.org/news/3gm3lJaUQgTKZJRm6TiBff/gbif-nodes-invited-to-join-pilot-for-metabarcoding-data-on-biodiversity[GBIF launched] a pilot phase for the https://www.gbif.org/metabarcoding-data-programme[Metabarcoding Data programme], intended to improve GBIF’s integration of DNA metabarcoding data on biodiversity. The pilot programme is open to GBIF node managers who wish to manage an instance of the MDT. Participating nodes are provided a hosted installation of the MDT. An MDT can be configured to operate in one of two modes:

* *Publishing mode*: MDT users can register datasets for publication through GBIF through the organizations to which they’re associated. This mode functions similarly to an installation of GBIF’s <<ipt>>.
* *Conversion-only mode*: MDT users can use it to reshape their dataset into a GBIF-ready <<dwc-a>> but must download them for hosting and publication on another repository, such as an IPT.

https://www.gbif.org/composition/7o3nbjPcY92vZxmjo6Z8E2/[Apply to manage an MDT] in the pilot programme (GBIF node managers primarily).

=== GBIF guides

* https://doi.org/10.35035/doc-vf1a-nr22[Publishing DNA-derived data through biodiversity data platforms] – was released in 2021 and has valuable supplementary in-depth information on publishing DNA-derived biodiversity data. As the MDT will handle several data preparation steps automatically, it is advisable to follow the information in the MDT user guide when in doubt.

NOTE: sections of central relevance: https://docs.gbif.org/publishing-dna-derived-data/en/#rationale[Rationale]; https://docs.gbif.org/publishing-dna-derived-data/en/#environmental-dna-as-a-source-for-dna-derived-occurrence-data[Environmental DNA as a source...]; https://docs.gbif.org/publishing-dna-derived-data/en/#dna-metabarcoding-sequence-derived-data[DNA metabarcodin data]; https://docs.gbif.org/publishing-dna-derived-data/en/#introduction-to-biodiversity-publishing[Introduction to publishing]; https://docs.gbif.org/publishing-dna-derived-data/en/#taxonomy-of-sequences[Taxonomy of sequences]; https://docs.gbif.org/publishing-dna-derived-data/en/#taxonomy-of-sequences[Mapping metabarcoding data].


=== More context about the MDT and DNA-derived data in GBIF

* Technical support hour for GBIF nodes: August 2025 (topic: MDT) (https://www.gbif.org/event/1GjkWCU2h24hoq2iV7X9wJ/technical-support-hour-for-gbif-nodes-august-2025[page+video])  
* Technical support hour for GBIF nodes: February 2024 (topic: DNA data publishing) (https://www.gbif.org/event/2vtOYk4ymZsLxQah4mfErG/[page+video])  
* eDNA data and GBIF at the 3rd https://secwww.jhuapl.edu/EventLink/Event/300[National Workshop^] on Marine eDNA, Maryland, USA, 2024 (https://www.youtube.com/watch?v=g9Y7gqR-y-w&list=PLQ_hsjucVlJSX-GhtXagFuloMGIx5tJMN&index=20[video])
* A quickly made example use of the MDT (old). (https://drive.google.com/file/d/1T27BYTxC_ky-Qn89lhvhlR0asRsLnbML/view?usp=sharing[video])
* GBIF briefing on Digital Sequence Information (DSI) (https://www.gbif.org/dsi-statement[web page, text])
* MDT administration and main differences with an IPT (https://vimeo.com/1200409964[video])


=== Selected short general videos on eDNA and DNA metabarcoding

* How we can detect pretty much anything - Hélène Morlon and Anna Papadopoulou - TED-Ed. (https://www.youtube.com/watch?v=bdwU_ZPk1cY[video])
* Biomonitoring using eDNA (environmental DNA) - Henrik's Lab. (https://www.youtube.com/watch?v=lxw6QvL1g70[video])
* What is Environmental DNA (eDNA)? – Illumina AMEA. (https://www.youtube.com/watch?v=b_MTVV5rYfo[video])
* Environmental DNA - World Wildlife Fund. (https://www.youtube.com/watch?v=4YXfZvEvUgc[video])
* Environmental DNA - Towards Next-Generation Biomonitoring - LeeseLab. (https://www.youtube.com/watch?v=cdV5BFaek_A[video])

=== Podcasts on eDNA and DNA metabarcoding

* What is Environmental DNA (eDNA) and How Can it Help? - A Conversation with Dr Shaun Wilkinson – Dr Adam Forbes. (https://www.youtube.com/watch?v=Se41PcD6H0g[podcast])

=== Various resources

* https://edna.dnabarcoding101.org/ - An introductory knowledge base to eDNA experiments  

=== Essential terms

Quick reference to essential terms for new users (links to <<glossary>>).  

* <<asv>>
* <<dwc-standard>>
* <<dwc-a>>
* <<dwc-term>>
* <<dna-derived, DNA-derived data (extension)>>
* <<endpoint>>
* <<occurrence>>
* <<occurrence_core>>
* <<otu>>
* <<otu-table>>

<<<
