[[tips_tricks]]
== Tips/Tricks and Advanced Usage 

=== Exclude samples and/or OTUs

Datasets most often include control samples (negative coltrols, blanks, positive controls, etc.). Such control samples do not represent relevant biodiversity and should be removed, as only real biological/environmental samples producing data that seems trustworthy should be shared. Likewise some sequences/OTUs may be suspected contamination (e.g. DNA from humans, pets, classical food items like tomato, potato, chicken, etc.). These should also be removed if possible.

TIP: The MDT will not include samples that are not present in both the *Samples* and *OTU_table*, and will not include OTUs that are not present in both the *Taxonomy* and *OTU_table* tables. Deleting (rows or IDs) of unwanted OTUs or Samples from the Taxonomy or Samples table means that they will be excluded from the final data although they are present in the OTU_table. This is thus an easy way of excluding OTUs or Samples – e.g. negative control samples, suspected contaminant species – from the data. NB: There will be warnings about the imperfect overlap of IDs during processing.

=== Using MDT through API

Some users have data in an already structured system and may want to build a publication pipeline that runs the MDT using API. This https://github.com/gbif/metabarcoding-data-toolkit-backend?tab=readme-ov-file#api[section in the MDT backend GitHub^] describes the API methods needed to run a dataset through the MDT, from raw data files to a Darwin Core Archive, published to GBIF.org. When running the MDT with APIs, it is possible to review the dataset through the UI at any step during the API interaction.

////
=== Getting the taxonomy into shape
////

<<<