[[introduction]]
== Introduction

=== Overview

GBIF offers access to extensive biodiversity data, mainly focusing on where and when species have been observed. These records, sourced from collections, surveys, and citizen science, include species names, dates, locations, and  additional details. GBIF also accomodates DNA-associated biodiversity data, including  DNA metabarcoding data, and the first version of a https://doi.org/10.35035/doc-vf1a-nr22[dna-publishing guide] was published in 2021. During consultations with the GBIF network and the research community in 2022 and 2023, it became clear that tools for easier data formatting and publishing were needed for DNA metabarcoding data.

THE_TOOL allows users with basic knowledge of data standards, GBIF and DNA (metabarcoding) data to reshape datasets in formats familiar to the DNA metabarcoding community – OTU table type datasets – into standardized datasets possible to publish to GBIF.

=== Target audiences

This guide is for anyone interested in publishing DNA metabarcoding data on GBIF (or OBIS, etc.), catering to both seasoned GBIF network members and researchers new to GBIF and the data publishing process.

[.underline]#All new users# are encouraged to review and go through both quick start guides to familiarize themselves with THE_TOOL, and then consult other relevant sections of the guide and ressources as needed.

=== Scope

* THE_TOOL handles *DNA metabarcoding datasets* in the shape of OTU tables/matrices and associated metadata. Datasets can be uploaded in a few selected template formats.
+
NOTE: THE_TOOL cannot handle or process raw sequencing files (fastq) from such datasets.
* THE_TOOL does [.underline]#not# handle DNA metagenomic data (shotgun sequencing data).
* THE_TOOL does [.underline]#not# handle other types of DNA-associated biodiversity data (specimen barcodes, qPCR, etc).

=== Getting started

A suggested approach could be:

* Watch this very brief https://vimeo.com/912170754[video] (originally made for the https://www.gbif.org/composition/lKyZFAUnIDv8kpf0CgZsS/technical-support-hour-for-gbif-nodes[Technical support hour for GBIF nodes])
* Run through the <<simplequick_start>>
* ...then the <<advanced_quick_start>>
* Select a <<templates, dataset template>>
* Adapt your own dataset to the template (see <<preparation_structure>>)
* Process the data in THE_TOOL
* Refer to the <<faq>>, the <<glossary>>, and the general https://doi.org/10.35035/doc-vf1a-nr22[dna-publishing guide] where needed.

=== Essential terms

There is a full glossary at the end of the document. The list here contains some essential terms for quick reference to new users. Terms link to the glossary. 

* <<asv>>
* <<dwc-standard>>
* <<dwc-a>>
* <<dwc-term>>
* <<dna-derived>>
* <<endpoint>>
* <<occurrence>>
* <<occurrence_core>>
* <<otu>>
* <<otu-table>>