[[introduction]]
== Introduction

****
The MDT and this guide are continuously evolving, so the guide may not fully reflect the current appearance and functionality of the MDT
****

=== Target audiences and scope

Anyone interested in learning to use the MDT for formatting and publishing DNA metabarcoding data to GBIF (or OBIS, etc.).

The Metabarcoding Data Toolkit can handle *DNA metabarcoding datasets* (aka amplicon sequence data) – specifically OTU tables and their associated metadata.

The MDT [.underline]#cannot# handle/process raw sequencing data (Fastq files, etc.)., metagenomic/shotgun datasets, or other types of DNA data (e.g., specimen barcodes, qPCR).

=== Getting started

==== Learn MDT Basics

* Begin with the <<simple_quick_start>> to get an overview of MDT.
* Supplement with the <<faq>> and <<glossary>>.

==== Learn to Process a Realistic Dataset

* Follow the <<detailed_guidance>> to process the provided example dataset.  
** Use the <<preparation_structure>>, <<faq>>, and <<glossary>> as references whenever needed.

==== Prepare and Process Your Own Dataset
_For users already familiar with the MDT usage (see above) looking to process their own datasets for publication._

* Prepare your dataset by carefully following the <<preparation_structure>>.  
* Process your dataset using the <<detailed_guidance>>, referring to the <<preparation_structure>>, <<faq>>, and <<glossary>> as necessary.

==== MDT Administration
_For MDT administrators_

* Explore the <<admin>> section.

==== Learn More / Additional Resources
_For those who wish to have a bit more context on GBIF, DNA-derived biodiversity data, Metabarcoding, environmental DNA, the Metabarcoding Data Programme, etc._

* Explore the <<background_resources>> and <<faq>>.

NOTE: The https://doi.org/10.35035/doc-vf1a-nr22[General GBIF DNA guide] has valuable general information on DNA biodiversity data, but is not yet updated with information on the MDT, so when in doubt, follow the information in this MDT user guide.

[[mdt_installations]]
=== MDT Installations

Users should choose the most relevant MDT based on their affiliation, region, project, or dataset. Prefer a GBIF node installation if available; otherwise, use a regional, thematic, or the general (GBIF conversion only) MDT. Use the MDT Sandbox for training/testing.

[cols="1,2", options="header"]
|===
| Region | MDT Installations

| Africa 
| Togo (https://tg.mdt.gbif.org/)

| Asia 
| (No installations)

| Europe & Central Asia 
| Europe & Central Asia (https://eca.mdt.gbif.org/) – Regional MDT +
Belgium (https://mdt.biodiversity.be/) +
Denmark (https://dk.mdt.gbif.org/) +
Estonia (https://mdt.plutof.ut.ee/) +
Finland (https://metabarcoding.laji.fi/) +
France (https://mdt.gbif.fr/) +
Luxembourg (https://mdt.gbif.mnhn.lu/) +
Norway (https://mdt.gbif.no/) +
Poland (https://mdt.gbif.pl/) +
United Kingdom (https://mdt-gbif.nbnatlas.org/)

| Latin America & the Caribbean 
| Latin America & the Caribbean (https://lac.mdt.gbif.org/) – Regional MDT +
Brazil (https://mdt.sibbr.gov.br/) +
Colombia (https://edna.biodiversidad.co/)

| North America 
| Canada (https://mdt.canadensys.net/) +
United States (https://mdt.gbif.us/)

| Oceania 
| Oceania (https://oceania.mdt.gbif.org/) – Regional MDT

| General MDTs 
| GBIF conversion only (https://mdt.gbif.org/) +
MDT Sandbox (Demo Installation) (https://mdt.gbif-test.org/)

| Thematic MDTs 
| OBIS (https://mdt.obis.org/)
|===