[[introduction]]
== Introduction

****
The MDT and this guide are continuously evolving, so the guide may not fully reflect the current appearance and functionality of the MDT
****

****
IMPORTANT: *Use your GBIF login* + 
All MDTs now use the _same https://www.gbif.org/user/profile[user account] as GBIF.org_.org. +
Also, you need a *password* for your GBIF account. If you originally signed up with GitHub or Google, click 'Forgot password' on the login page to set up a password. +
The (test) MDT used UAT user profiles during early development, but this is no longer the case.
****

=== Target audiences and scope

This user guide is for anyone interested in learning to use the MDT for formatting and publishing DNA metabarcoding data to GBIF (or OBIS, etc.).

What the Metabarcoding Data Toolkit can do:

* Handle *DNA metabarcoding datasets* – specifically OTU tables and their associated metadata.
* Accept dataset uploads in a few supported template formats.

What the MDT [.underline]#cannot# do:

* Bioinformatic processing/analysis of raw sequencing data (Fastq files, etc.). Use dedicated bioinformatic tools and pipelines for that (dada2, Qiime2, Vsearch, Usearch, etc.).
* Handle DNA metagenomic datasets (e.g., shotgun sequencing) - 
* Handle other DNA-associated biodiversity data types (e.g., specimen barcodes, qPCR).

=== Getting started

*Getting Started: Learn MDT Basics* +
_Perfect for first-time users or those who want a quick overview of what the MDT is and how it works._

* Begin with the <<simple_quick_start>> to get an overview of MDT.

*Learn to Process a Realistic Dataset* +
_A step-by-step guide for users looking to understand how to handle and process a dataset using the MDT._

* Follow the <<detailed_guidance>> to process the example dataset.  
** Use the <<preparation_structure, preparation instructions>>, <<faq>>, and <<glossary>> as references whenever needed.

*Prepare Your Own Dataset* +
_Designed for users already familiar with MDT basics who are ready to prepare their own datasets for publication._

* Adapt your dataset to one of the templates by carefully following the <<preparation_structure, preparation instructions>>.  
* Process your dataset using the <<detailed_guidance>>, referring to the <<preparation_structure, preparation instructions>>, <<faq>>, and <<glossary>> as necessary.

*MDT Administration* +
_For MDT managers who have a grasp of the basics and need guidance on managing and maintaining the tool effectively._

* Explore the <<admin>> section.

*Learn More / Additional Resources* +
_For those who wish to have a bit more context on GBIF, DNA-derived biodiversity data, Metabarcoding, environmental DNA, the Metabarcoding Data Programme, etc._

* Explore the <<background_resources>> and <<faq>>.

NOTE: The https://doi.org/10.35035/doc-vf1a-nr22[General GBIF DNA guide] has valuable general information on DNA biodiversity data, but is not yet updated with information on the MDT, so when in doubt, follow the information in this MDT user guide.

<<<