[[introduction]]
== Introduction

IMPORTANT: #Both the MDT and this guide are continuously being developed. Even when using the most recent version of the guide, it may be slightly out of sync with the exact appearance and functionality of the MDT.#

IMPORTANT: #The guide refers to a https://mdt.gbif-uat.org/[MDT Sandbox (Demo Installation)] and a https://mdt.gbif.org/[GBIF Conversion MDT]. These are not yet online! Currently these link to test installation: https://mdt.gbif-uat.org/ that uses UAT LOGIN! (not GBIF login)#

=== Target audiences and scope

This user guide is for anyone interested in learning to use the MDT for formatting and publishing DNA metabarcoding data to GBIF (or OBIS, etc.).

What the Metabarcoding Data Toolkit can do:

* Handle *DNA metabarcoding datasets* – specifically OTU tables and their associated metadata.
* Accept dataset uploads in a few supported template formats.

What the MDT [.underline]#cannot# do:

* Bioinformatic processing/analysis of raw sequencing data (Fastq files, etc.). Use dedicated bioinformatic tools and pipelines for that (dada2, Qiime2, Vsearch, Usearch, etc.).
* Handle DNA metagenomic datasets (e.g., shotgun sequencing) - 
* Handle other DNA-associated biodiversity data types (e.g., specimen barcodes, qPCR).

=== Getting started

If you are familiar with the basics of DNA metabarcoding data and/or just want to learn the basics of using the MDT:

* Work through the <<simple_quick_start>> using the https://mdt.gbif-uat.org/[MDT Sandbox (Demo Installation)].
* Process the example dataset following the <<detailed_guidance>>. 
** Refer to the <<preparation_structure, preparation instructions>>, the <<faq>> and the <<glossary>> as needed.

If you know the basics of the MDT and want to prepare and/or publish a real dataset:

* Adapt your dataset to a template following the (see <<preparation_structure, preparation instructions>>) carefully.
* Process the dataset following the <<detailed_guidance>>, while referreing to the <<preparation_structure, preparation instructions>>, the <<faq>>, and the <<glossary>> as needed.


NOTE: The https://doi.org/10.35035/doc-vf1a-nr22[general GBIF DNA guide] has valuable general information on DNA biodiversity data, but is not yet updated with information on the MDT, so when in doubt, follow the information in this MDT user guide.

<<<