[[introduction]]
== Introduction

****
The MDT and this guide are continuously evolving, so the guide may not fully reflect the current appearance and functionality of the MDT
****

=== Target audiences and scope

Anyone interested in learning to use the MDT for formatting and publishing DNA metabarcoding data to GBIF (or OBIS, etc.).

What the Metabarcoding Data Toolkit can do:

* Handle *DNA metabarcoding datasets* – specifically OTU tables and their associated metadata.

What the MDT [.underline]#cannot# do:

* Bioinformatic processing/analysis of raw sequencing data (Fastq files, etc.).
* Handle DNA metagenomic datasets (e.g., shotgun sequencing) - 
* Handle other DNA-associated biodiversity data types (e.g., specimen barcodes, qPCR).

=== Getting started

*Learn MDT Basics* +
_For first-time users or those who want a quick overview of what the MDT is and how it works._

* Begin with the <<simple_quick_start>> to get an overview of MDT.

*Learn to Process a Realistic Dataset* +
_For users looking to understand how to handle and process a dataset using the MDT._

* Follow the <<detailed_guidance>> to process the provided example dataset.  
** Use the <<preparation instructions>>, <<faq>>, and <<glossary>> as references whenever needed.

*Prepare Your Own Dataset* +
_For users already familiar with MDT basics who are ready to prepare their own datasets for publication._

* Adapt your dataset to one of the templates by carefully following the <<preparation instructions>>.  
* Process your dataset using the <<detailed_guidance>>, referring to the <<preparation_structure, <<faq>>, and <<glossary>> as necessary.

*MDT Administration* +
_For MDT administrators who have a grasp of the basics and need guidance on managing and maintaining the tool effectively._

* Explore the <<admin>> section.

*Learn More / Additional Resources* +
_For those who wish to have a bit more context on GBIF, DNA-derived biodiversity data, Metabarcoding, environmental DNA, the Metabarcoding Data Programme, etc._

* Explore the <<background_resources>> and <<faq>>.

NOTE: The https://doi.org/10.35035/doc-vf1a-nr22[General GBIF DNA guide] has valuable general information on DNA biodiversity data, but is not yet updated with information on the MDT, so when in doubt, follow the information in this MDT user guide.

[[mdt_installations]]
=== MDT Installations

Users should choose the most relevant MDT based on their affiliation, region, project, or dataset. Prefer a GBIF node installation if available; otherwise, use a regional, thematic, or the general (GBIF conversion only) MDT. Use the MDT Sandbox for training/testing.

**GBIF Node MDTs**

* Africa: https://tg.mdt.gbif.org/[Togo]
* Asia: (No installations)
* Europe & Central Asia: 
**  https://mdt.biodiversity.be/[Belgium] 
**  https://dk.mdt.gbif.org/[Denmark] 
**  https://metabarcoding.laji.fi/[Finland] 
**  https://mdt.gbif.fr/[France] 
**  https://mdt.gbif.mnhn.lu/[Luxembourg] 
**  https://mdt.gbif.no/[Norway] 
**  https://mdt.gbif.pl/[Poland] 
**  https://mdt-gbif.nbnatlas.org/[United Kingdom]
* Latin America & the Caribbean: 
**  https://mdt.sibbr.gov.br/[Brazil] 
**  https://edna.biodiversidad.co/[Colombia]
* North America: 
**  https://data.canadensys.net/mdt/[Canada] 
**  https://mdt.gbif.us/[United States]
* Oceania: (No installations)

**Regional MDTs**  

* https://eca.mdt.gbif.org/[Europe & Central Asia]    
* https://lac.mdt.gbif.org/[Latin America & the Caribbean]  

**General MDTs**  

* https://mdt.gbif.org/[GBIF conversion only]  
* https://mdt.gbif-test.org/[MDT Sandbox (Demo Installation)]

**Thematic MDTs**  

https://mdt.obis.org/[OBIS]

<<<