[[introduction]]
== Introduction

IMPORTANT: #Both the MDT and this guide are continuously being developed. Even when using the most recent version of the guide, it may be slightly out of sync with the exact appearance and functionality of the MDT.#

=== Target audiences and scope

This user guide is for anyone interested in learning to use the MDT for formatting and publishing DNA metabarcoding data to GBIF (or OBIS, etc.).

What the Metabarcoding Data Toolkit can do:

* Handle *DNA metabarcoding datasets* – specifically OTU tables and their associated metadata.
* Accept dataset uploads in a few supported template formats.

What the MDT [.underline]#cannot# do:

* Bioinformatic processing/analysis of raw sequencing data (Fastq files, etc.). Use dedicated bioinformatic tools and pipelines for that (dada2, Qiime2, Vsearch, Usearch, etc.).
* Handle DNA metagenomic datasets (e.g., shotgun sequencing) - 
* Handle other DNA-associated biodiversity data types (e.g., specimen barcodes, qPCR).

=== Getting started

If you are familiar with the basics of DNA metabarcoding data and/or just want to learn the basics of using the MDT:

* Work through the <<simple_quick_start>> using the GBIF demo MDT installation.
* Browse/explore this https://mdt.gbif-uat.org/dataset/3d4e6748-df68-4047-ab04-ac3c3baa7840/review[example dataset 2] in the demo MDT.
* Upload and process <<example2>> in the GBIF demo MDT installation following the steps in the <<detailed_guidance>>
** Refer to the <<preparation_structure, preparation instructions>>, the <<detailed_guidance>>, the <<faq>>, and the <<glossary>> as needed.

If you know the basics of the MDT and want to prepare your own dataset:

* Select a <<templates, dataset template>> suitable for your data.
* Adapt your dataset to the template following the (see <<preparation_structure, preparation instructions>>).
** You may use the <<example2>> as a model of a well-formatted dataset.
* Upload and process the data in an MDT (a hosted MDT or the demo installation).
** Refer to the <<preparation_structure, preparation instructions>>, the <<detailed_guidance>>, the <<faq>>, and the <<glossary>> as needed.


NOTE: The https://doi.org/10.35035/doc-vf1a-nr22[general GBIF DNA guide] has valuable general information on DNA biodiversity data, but is not yet updated with information on the MDT, so when in doubt, follow the information in this MDT user guide.

<<<